apiVersion: v1
kind: Service
metadata:
  name: article-service
spec:
  selector:
    app: article
  ports:
    - name: grpc
      protocol: TCP
      port: 50052
      targetPort: 50051
    - name: metrics
      protocol: TCP
      port: 2224
      targetPort: 2223
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-d
spec:
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: article
    spec:
      restartPolicy: Always
      containers:
        - envFrom:
            - configMapRef:
                name: article-env
          image: krixlion/dev_forum-article:0.1.0
          imagePullPolicy: IfNotPresent
          name: server
          ports:
            - name: grpc
              containerPort: 50051
            - name: metrics
              containerPort: 2223
          resources:
            limits:
              cpu: 20m
              memory: 150Mi
            requests:
              cpu: 5m
              memory: 80Mi
          volumeMounts:
            - name: tls-certs
              mountPath: /tls
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: tls-secret-article
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-certificate-article
  labels:
    app: article
spec:
  secretName: tls-secret-article
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
  dnsNames:
    - "article-service"
  issuerRef:
    name: root-issuer
    kind: Issuer
