apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eventstore-cluster
spec:
  serviceName: eventstore-service
  selector:
    matchLabels:
      database: eventstore
  replicas: 1
  volumeClaimTemplates:
    - metadata:
        name: eventstore-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 300Mi
  template:
    metadata:
      labels:
        database: eventstore
    spec:
      containers:
        - image: eventstore/eventstore:22.10.0-buster-slim
          name: eventstoredb
          ports:
            - name: grpc
              containerPort: 2113
              protocol: TCP
          env:
            - name: EVENTSTORE_CLUSTER_SIZE
              value: "1"
            - name: EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP
              value: "true"
            - name: EVENTSTORE_HTTP_PORT
              value: "2113"
            - name: EVENTSTORE_INSECURE
              value: "true"
            - name: EVENTSTORE_RUN_PROJECTIONS
              value: All
            - name: EVENTSTORE_START_STANDARD_PROJECTIONS
              value: "true"
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 100Mi
          volumeMounts:
            - mountPath: /var/lib/eventstore
              name: eventstore-data
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: eventstore-service
spec:
  clusterIP: None
  selector:
    database: eventstore
  ports:
    - name: http
      port: 2113
      protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  # DON'T PREFIX THE NAME AS "eventstore", USE "eventstoredb" INSTEAD.
  # Kubernetes will configure services using ENV vars prefixed with the service name.
  # EventStoreDB loads configuration from ENV and reads all values prefixed with "EVENTSTORE_".
  # This will cause the DB to try and apply Kubernetes service settings and either
  # crash or overwrite some of the settings, for example used http port.
  name: eventstoredb-service-ui
spec:
  type: LoadBalancer
  selector:
    database: eventstore
    statefulset.kubernetes.io/pod-name: eventstore-cluster-0
  ports:
    - name: http
      port: 2113
      protocol: TCP
