apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
spec:
  serviceName: redis-service
  volumeClaimTemplates:
    - metadata:
        name: redis-data
        labels:
          database: redis
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 300Mi
  replicas: 1
  template:
    metadata:
      labels:
        database: redis
    spec:
      containers:
        - args:
            - redis-server
            - --port 6379
          image: redis:7.0.5-alpine
          name: redis
          resources:
            limits:
              cpu: 750m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 10Mi
          volumeMounts:
            - name: redis-data
              mountPath: /data
            # - name: redis-config
            #   mountPath: /usr/local/etc/redis/redis.conf
            #   subPath: redis.conf
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    database: redis
  ports:
    - port: 6379
      targetPort: 6379
