version: '3'

services:

  service:
    container_name: "${PROJECT_NAME}_${AGGREGATE_ID}-${SERVICE_ENV}"
    restart: unless-stopped
    image: krixlion/go-reflex-dlv:${GO_VERSION}
    environment:
      - BUILD_ARGS=-race cmd/main.go
      - RUN_ARGS=-p ${GRPC_PORT}
      - DEBUG_PORT=${DEBUG_PORT}
      # - DELVE_ARGS=--continue
    ports:
      - ${GRPC_PORT}:${GRPC_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    volumes:
      - .:/app
    depends_on:
      - eventstore
      - redis
      - rabbitmq
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 20M

  eventstore:
    image: eventstore/eventstore:22.10.0-buster-slim
    restart: unless-stopped
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      # - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=${DB_WRITE_PORT}
      - EVENTSTORE_INSECURE=true
      # - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
    # HTTP, gRPC port
      - "${DB_WRITE_PORT}:${DB_WRITE_PORT}"
    volumes:
        - eventstore-data:/var/lib/eventstore
    # deploy:
      # resources:
        # limits:
          # cpus: '0.50'
          # memory: 550M
        # reservations:
          # cpus: '0.25'
          # memory: 20M

  redis:
    image: redis:7.0.5-alpine
    restart: unless-stopped
    command: redis-server  --port ${DB_READ_PORT} #/usr/local/etc/redis/redis.conf
    ports:
      - ${DB_READ_PORT}:${DB_READ_PORT}
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    # deploy:
      # resources:
        # limits:
          # cpus: '0.50'
          # memory: 350M
        # reservations:
          # cpus: '0.25'
          # memory: 10M

  rabbitmq:
    image: rabbitmq:3.11.3-alpine
    restart: unless-stopped
    ports:
    # AMQP port
    - 5672:5672
    # HTTP port
    - 15672:15672
    volumes:
    - rabbitmq-data:/var/lib/rabbitmq/
    - rabbitmq-logs:/var/log/rabbitmq
    # deploy:
      # resources:
        # limits:
          # cpus: '0.50'
          # memory: 350M
        # reservations:
          # cpus: '0.25'
          # memory: 20M

volumes:
  eventstore-data:
  redis-data:
  rabbitmq-logs:
  rabbitmq-data: