version: '3'

services:

  service:
    container_name: "${PROJECT_NAME}_${AGGREGATE_ID}-${SERVICE_ENV}"
    image: krixlion/go-reflex-dlv:${GO_VERSION}
    environment:
      - BUILD_ARGS=${BUILD_ARGS}
      - RUN_ARGS=${RUN_ARGS}
      - DEBUG_PORT=${DEBUG_PORT}
    volumes:
      - .:/app
    ports:
      - ${GRPC_PORT}:${GRPC_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}

  eventstore:
    image: eventstore/eventstore:22.10.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      # - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=${DB_WRITE_PORT}
      - EVENTSTORE_INSECURE=true
      # - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
    # HTTP, gRPC port
      - "${DB_WRITE_PORT}:${DB_WRITE_PORT}"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

volumes:
  eventstore-volume-data:
  eventstore-volume-logs: