apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - cert.yaml

patches:
  - path: deployment-patches.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: article-d
