apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-certificate-article
  labels:
    app: article
spec:
  secretName: tls-secret-article
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
  dnsNames:
    - "article-service"
  issuerRef:
    name: root-issuer
    kind: Issuer
