on:
    push:
      branches:
        - dev
    pull_request:
      branches: 
        - '*'
      paths-ignore:
        - '**.md'
        - '.vscode/**'
        - 'deployment/**'
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true
      - uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          only-new-issues: false
  